import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const generateInvoiceSummaryPDF = async (summaryData, filename) => {
  const {
    start,
    end,
    totalTransactions,
    totalAmount,
    transactions,
  } = summaryData;

  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  const filePath = path.join(__dirname, '..', 'invoices', filename);
  doc.pipe(fs.createWriteStream(filePath));

  // Add header
  doc
    .rect(0, 0, doc.page.width, 100)
    .fill('#2b6cb0');
    
  doc
    .fillColor('#ffffff')
    .fontSize(20)
    .text('Transaction Summary Invoice', 50, 30, { align: 'left' })
    .fontSize(12)
    .text('Invoice Date: ' + new Date().toLocaleDateString(), 50, 60)
    .text(`Period: ${new Date(start).toDateString()} - ${new Date(end).toDateString()}`, 50, 80)

  // Company Info
  doc
    .fillColor('#000000')
    .fontSize(10)
    .text('FinConnect', 50, 120)
    // .text('WebKode25', 50, 135)
    .text('Created by (MetaStackers) Team', 50, 135)

  // Summary Highlights
  doc
    .roundedRect(50, 190, 500, 60, 8)
    .fill('#f7fafc');
    
  doc
    .fillColor('#2d3748')
    .fontSize(14)
    .text('Summary', 70, 205)
    .fontSize(12)
    .text(`Total Transactions: ${totalTransactions}`, 70, 225)
    .text(`Total Amount: $${totalAmount.toLocaleString('en-IN')}`, 70, 240);

  // Transactions Table
  let y = 280;
  
  // Table Header
  doc
    .fillColor('#ffffff')
    .rect(50, y, 500, 20)
    .fill('#4a5568');
    
  doc
    .fontSize(10)
    .text('Date', 60, y + 5)
    .text('Transaction ID', 150, y + 5)
    .text('Amount ($)', 450, y + 5, { width: 90, align: 'right' });

  y += 25;

  // Transactions Rows
  transactions.forEach((tx, index) => {
    if(index % 2 === 0) {
      doc
        .fillColor('#f7fafc')
        .rect(50, y, 500, 20)
        .fill();
    }
    
    doc
      .fillColor('#2d3748')
      .fontSize(10)
      .text(new Date(tx.timestamp).toLocaleDateString(), 60, y + 5)
      // .text(tx._id.slice(0, 8) + '...', 150, y + 5)
      .text(tx.amount.toLocaleString('en-IN'), 450, y + 5, { width: 90, align: 'right' });

    // Add separator
    doc
      .moveTo(50, y + 20)
      .lineTo(550, y + 20)
      .strokeColor('#e2e8f0')
      .lineWidth(0.5)
      .stroke();

    y += 20;
  });

  // Total Section
  doc
    .fillColor('#2d3748')
    .fontSize(12)
    .text('Grand Total:', 400, y + 20)
    .font('Helvetica-Bold')
    .text(`$${totalAmount.toLocaleString('en-IN')}`, 450, y + 20, { width: 90, align: 'right' })
    .font('Helvetica');

  // Footer
  doc
    .fontSize(8)
    .fillColor('#718096')
    .text('Thank you for your business!', 50, doc.page.height - 50)
    .text('Generated by Your Company Name', 50, doc.page.height - 35)
    .text(`Page ${doc.page.number}`, 500, doc.page.height - 35, { align: 'right' });

  doc.end();
  return filePath;
};

export default generateInvoiceSummaryPDF;